name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Windows Binary
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.30.2'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitURL: https://github.com/microsoft/vcpkg.git
          vcpkgGitCommitId: '6421c16ca7972b33f1f0a881a83acac7b40c8b50'
          vcpkgDirectory: '${{ runner.temp }}/vcpkg'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure CMake
        run: |
          cmake -S . -B build `
                -G "Ninja" `
                -DCMAKE_BUILD_TYPE=${env:BUILD_TYPE} `
                -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
        shell: pwsh

      - name: Build
        run: cmake --build build
        shell: pwsh

      - name: Prepare artifact
        run: |
          if (Test-Path dist) { Remove-Item dist -Recurse -Force }
          New-Item -ItemType Directory -Path dist | Out-Null
          Copy-Item build/motion_detection.exe dist/
          Push-Location dist
          $zipName = "motion_detection-$env:BUILD_TYPE-win-x64.zip"
          Compress-Archive -Path motion_detection.exe -DestinationPath $zipName -Force
          Pop-Location
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: motion_detection-${{ env.BUILD_TYPE }}-win-x64
          path: dist/motion_detection-${{ env.BUILD_TYPE }}-win-x64.zip
          if-no-files-found: error

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/motion_detection-${{ env.BUILD_TYPE }}-win-x64.zip
          generate_release_notes: true
